### ISSUE TITLE
Request for License

### ISSUE THREAD

**Issue by probinso** [jashubbard/psycomputing#1]
I was interested in working through some of this material; which might result in modifying, forking, or adopting parts into some separate projects. I don't, however, want to violate any intended use concerns that you may have. Could you add a license to this repository?

Much thanks for your consideration,
-- Philip

**Comment by jashubbard** [comment]
Hi Philip, 

Thanks for your interest. I just added a GPLv3 license. I would say if you're interested in disseminating the material for a class, blog, or other teaching purpose, kindly reference the original repository  :-)

Thanks, 
Jason
